version: "3.9"

services:
  # Kafka infra
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Account microservice
  account_service:
    build: ./account_service
    container_name: account_service
    env_file:
      - ./account_service/.env
    ports:
      - "4001:4001"
    depends_on:
      - kafka

  # Chat microservice
  chat_service:
    build: ./chat_service
    container_name: chat_service
    env_file:
      - ./chat_service/.env
    ports:
      - "4002:4002"
    depends_on:
      - kafka
      - account_service

  # Gateway microservice
  gateway_service:
    build: ./gateway_service
    container_name: gateway_service
    env_file:
      - ./gateway_service/.env
    ports:
      - "4000:4000"
    depends_on:
      - account_service
      - chat_service
